### PR TITLE
Fake location lookup is now triggered via fictional phone number

### LINKED ISSUE #56: Dummy feature to check location on localhost
I am configuring OPENGMLC on my localhost , when I do /restomm with an msisdn , it shows empty response which is ok, there needs to be some simulator or dummy msisdn that I can pass to it and it can send me response.

Thanks 
#53

### PR DESCRIPTION
**Pull request by Vanit**
The dummy number 19395550113 was chosen for 2 reasons:
- It falls in the officially reserved fictional 555-0100 to 555-0199 range in the US, so should never clash with a real number
- It's The Simpsons home phone number

Resolves #56

### CODE REVIEW

**Comment by FerUy** [comment]
@Monix please update README.md to the latest and commit again.

**Comment by Vanit** [comment]
Still new to this so apologies if I misunderstood - I've now merged in the new upstream changes, is that what was missing?

**Comment by FerUy** [comment]
Hi @Monix, no worries. You need to update your local branch after a PR is merged with master, otherwise you might be working with older versions. In this case it's not showing you conflicts as it's only a text file. Don't worry, I'll take care of this.

**Comment by FerUy** [comment]
@Monix, build #42 including this fix is working as expected. :+1:

**Pull request merged**
