### PR TITLE
Merge first_build branch with master

### PR DESCRIPTION
**Pull request by FerUy**
@vetss this merge covers your instructions from 1 to 8.

### CODE REVIEW

**Comment by FerUy** [comment]
@angrygreenfrogs @vetss do you agree in deleting this branch now and continue working on ts-1.0.0 as for TelScale v1.0.0?

**Comment by angrygreenfrogs** [comment]
Sounds good, @FerUy 

All of the branches in this project have been merged and are quite old - I'm going to clean them up.

**Comment by FerUy** [comment]
Cool, thanks @angrygreenfrogs

**Comment by FerUy** [comment]
Cool, thanks @angrygreenfrogs.
Just a brief update, ts-1.0.0 was a not proper branch name for this environment, so I created **gmlc1.0** instead. Let's use that please.

**Comment by angrygreenfrogs** [comment]
Sounds fine @FerUy 

Although I've noticed that in many of the other projects, it's common to create a branch for specific issues/features (e.g. "issue341" as a branch), and then merge them in... so I'm not sure of the process flow if we have a main gmlc1.0 branch?

Would you like us to create branches for individual issues/features, and then submit pull requests to gmlc1.0, where we'll collect all of the changes together and merge them master only when the release is ready?

**Comment by FerUy** [comment]
Sure @angrygreenfrogs, I like the idea. Go ahead!

**Pull request merged**
